{
    'name': 'Partner Sensitivity',
    'summary': "Adds sensativity levels to partners.",
    'author': "Patrick Wilson, Odoo Community Association (OCA)",
    'website': "https://github.com/OCA/partner-contact",
    'category': 'Extra Tools',
    'version': '12.0.1.0.0',
    'license': 'AGPL-3',
    'depends': ['base',
                'contacts',
                ],
    'data': [
        'views/res_partner.xml',
        'views/partner_sensitivity.xml',
        'security/ir.model.access.csv',
        'data/partner_sensitivity_data.xml',
    ],
    'application': True,
    'development_status': 'Beta',
    'maintainers': ['patrickrwilson'],
}
