from . import agreement_type
from . import circuit_segment
from . import equipment_mediatype
from . import equipment_paneltype
from . import equipment_phyport
from . import equipment_pluggabletype
from . import equipment_portdefinition
from . import equipment_portprotocol
from . import equipment_role
from . import equipment_slot
from . import equipment_slottype
from . import equipment_status
from . import equipment_vport
from . import equipment
from . import partner_agreement
from . import product
from . import res_partner
