from . import partner_agreement
from . import agreement_type
from . import circuit_segment
from . import res_partner
from . import equipment
from . import equipment_phyport
from . import equipment_vport
from . import equipment_role
from . import equipment_slottype
from . import equipment_card
from . import equipment_shelf
from . import equipment_portprotocol
from . import equipment_pluggable
from . import equipment_pluggabletype
from . import equipment_mediatype
from . import equipment_status
