from odoo import models, fields

class CircuitSegment(models.Model):
    _name = 'agreement_circuits.segment'

    name = fields.Char(string="Title", required=True)
    internal_circuit_id = fields.Char(string="Internal Circuit ID")
    circuit_type = fields.Many2one('equipment.circuittype', string="Circuit Type")
    pricing_type = fields.Selection([('burstable', 'Burstable'),('fixed_rate', 'Fixed Rate')], string="Pricing Type")
    min_mrc = fields.Integer(string="Minimum MRC")
    price_per_mb = fields.Integer(string="Price / Mb")
    nrc = fields.Integer(string="NRC")
    comments = fields.Text(string="Comments")
    spacer = fields.Char(string="Spacer")

    parent = fields.Many2one('partner_agreement.agreement', string="Parent")

    a_carrier = fields.Many2one('res.partner', string="A Carrier")
    a_endpoint = fields.Many2one('res.partner', string="Name")
    a_endpoint_address = fields.Char(related='a_endpoint.contact_address', string="Address")
    a_endpoint_street = fields.Char(related='a_endpoint.street', string="Street")
    a_endpoint_street2 = fields.Char(related='a_endpoint.street2', string="Street 2")
    a_endpoint_city = fields.Char(related='a_endpoint.city', string="City")
    a_endpoint_state = fields.Many2one(related='a_endpoint.state_id', string="State")
    a_endpoint_zip = fields.Char(related='a_endpoint.zip', string="Zip")
    a_endpoint_handoff = fields.Text(string="Handoff")
    a_endpoint_demarc = fields.Text(string="Demarc")
    a_endpoint_extended_demarc = fields.Text(string="Extended Demarc")
    a_facility = fields.Many2one('maintenance.equipment', string="Facility A")
    a_image = fields.Binary(related='a_facility.image', string="Image")
    a_facility_manufacturer = fields.Many2one(related='a_facility.manufacturer', string="Manufactuer")
    a_facility_model = fields.Char(related='a_facility.model', string="Model")
    a_site_contact = fields.Many2one('res.partner', string="Site POC")
    a_phone = fields.Char(related='a_site_contact.phone', string="Phone")
    a_cell = fields.Char(related='a_site_contact.mobile', string="Cell")
    a_fax = fields.Char(string="Fax")
    a_email = fields.Char(related='a_site_contact.email', string="E-mail")
    a_secondary_contact = fields.Many2one('res.partner', string="Secondary POC")
    a_secondary_phone = fields.Char(related='a_secondary_contact.phone', string="Secondary Phone")
    a_loa_cfa = fields.Text(string="LOA/CFA", help="Letter of Authority/Customer Facility Assignment")
    a_slot = fields.Many2one('equipment.slot', string="Slot")
    a_card = fields.Many2one('maintenance.equipment', string="Card")
    a_port = fields.Many2one('equipment.phyport', string="Port")
    a_port_protocol = fields.Many2one('equipment.portprotocol', string="Protocol")
    a_rack = fields.Many2one('maintenance.equipment', string="Rack")

    z_carrier = fields.Many2one('res.partner', string="Z Carrier")
    z_endpoint = fields.Many2one('res.partner', string="Name")
    z_endpoint_address = fields.Char(related='z_endpoint.contact_address', string="Address")
    z_endpoint_street = fields.Char(related='z_endpoint.street', string="Street")
    z_endpoint_street2 = fields.Char(related='z_endpoint.street2', string="Street 2")
    z_endpoint_city = fields.Char(related='z_endpoint.city', string="City")
    z_endpoint_state = fields.Many2one(related='z_endpoint.state_id', string="State")
    z_endpoint_zip = fields.Char(related='z_endpoint.zip', string="Zip")
    z_endpoint_handoff = fields.Text(string="Handoff")
    z_endpoint_demarc = fields.Text(string="Demarc")
    z_endpoint_extended_demarc = fields.Text(string="Extended Demarc")
    z_facility = fields.Many2one('maintenance.equipment', string="Facility Z")
    z_image = fields.Binary(related='z_facility.image')
    z_facility_manufacturer = fields.Many2one(related='z_facility.manufacturer', string="Manufactuer")
    z_facility_model = fields.Char(related='z_facility.model', string="Model")
    z_site_contact = fields.Many2one('res.partner', string="Site POC")
    z_phone = fields.Char(related='z_site_contact.phone', string="Phone")
    z_cell = fields.Char(related='z_site_contact.mobile', string="Cell")
    z_fax = fields.Char(string="Fax")
    z_email = fields.Char(related='z_site_contact.email', string="E-mail")
    z_secondary_contact = fields.Many2one('res.partner', string="Secondary POC")
    z_secondary_phone = fields.Char(related='z_secondary_contact.phone', string="Secondary Phone")
    z_loa_cfa = fields.Text(string="LOA/CFA", help="Letter of Authority/Customer Facility Assignment")
    z_slot = fields.Many2one('equipment.slot', string="Slot")
    z_card = fields.Many2one('maintenance.equipment', string="Card")
    z_port = fields.Many2one('equipment.phyport', string="Port")
    z_port_protocol = fields.Many2one('equipment.portprotocol', string="Protocol")
    z_rack = fields.Many2one('maintenance.equipment', string="Rack")
