# Copyright (C) 2018 Open Source Integrators
# License Proprietary. Do not copy, share nor distribute.

{
    'name': 'Pavlov Media',
    'summary': 'Pavlov Media Configuration and Data',
    'version': '11.0.1.0.0',
    'license': 'Other proprietary',
    'author': 'Open Source Integrators',
    'maintainer': 'Open Source Integrators',
    'website': 'https://www.opensourceintegrators.com',
    'depends': [
        # Odoo and Enterprise Addons
        'account_accountant',
        'board',
        'crm',
        'delivery_fedex',
        'delivery_ups',
        'documents',
        'fleet',
        'lunch',
        'maintenance',
        'marketing_automation',
        'mass_mailing',
        'helpdesk',
        'hr_appraisal',
        'hr_attendance',
        'hr_expense',
        'hr_holidays',
        'hr_timesheet',
        'mrp',
        'mrp_plm',
        'project',
        'purchase',
        'sale_subscription',
        'sales_team',
        'sign',
        'stock_barcode',
        'survey',
        # OCA Addons
        # 'account_payment_credit_card',
        # 'agreement_maintenance',
        # 'agreement_mrp',
        # 'agreement_project',
        # 'agreement_repair',
        # 'agreement_stock',
        'auditlog',
        'base_partner_sequence',
        'fieldservice',
        # 'fieldservice_account',
        # 'fieldservice_agreement',
        # 'fieldservice_delivery',
        'fieldservice_distribution',
        # 'fieldservice_maintenance',
        # 'fieldservice_partner_multi_relation',
        # 'fieldservice_repair',
        'fieldservice_sale',
        'fieldservice_skill',
        # 'fieldservice_stock',
        # 'fieldservice_substatus',
        'l10n_us_form_1099',
        'mass_editing',
        'partner_fax',
        # 'partner_priority',
        # 'partner_time_to_pay',
        'product_template_tags',
        # 'stock_production_lot_warranty',
        'project_status',
        'project_category',
        'project_tags',
        'project_stage_closed',
        # 'project_milestone',
        # 'project_template',
        # OSI Addons
        # 'agreement_helpdesk',
        # 'agreement_rma',
        # 'agreement_sale_subscription',
        # 'fieldservice_googlemaps',
        # 'fieldservice_helpdesk_stock',
        # 'helpdesk_fieldservice_agreement',
        'helpdesk_phone',
        'helpdesk_resolution',
        'helpdesk_scope',
        # 'helpdesk_stock',
        'helpdesk_ticket_parent',
        'helpdesk_ticket_to_task',
        'helpdesk_ticket_type_default_priority',
        # Other Modules that might be submitted to community or OSI
        'fsm_location_infrastructure',
        'helpdesk_documents',
        'partner_sensitivity',
        'project_task_timer',
        'helpdesk_timer',
        # Private Addons
        'bwchange',
        'intranet',
        'powerbi',
        'pavlov_media_contact',
        'pavlov_media_fieldservice',
        'pavlov_media_project',
        'pavlov_media_helpdesk',
        'external_systems',
    ],
    'data': [
    ],
    'application': True,
    'sequence': 0,
}
